version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: harbour-postgres
    environment:
      POSTGRES_DB: harbour_advisor
      POSTGRES_USER: harbour_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U harbour_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: harbour-backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://harbour_user:${POSTGRES_PASSWORD:-changeme}@postgres:5432/harbour_advisor
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-change-in-production}
      ALLOWED_ORIGINS: http://localhost:8501,http://localhost:3000
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - ./advisor:/app/advisor
      - ./data:/app/data
    restart: unless-stopped

  # Streamlit Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: harbour-frontend
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: http://backend:8000
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    depends_on:
      - backend
    volumes:
      - ./app.py:/app/app.py
      - ./ui_components.py:/app/ui_components.py
      - ./calendar_view.py:/app/calendar_view.py
      - ./realtime_hub.py:/app/realtime_hub.py
      - ./data:/app/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: harbour-network
